import React from 'react';

export const organDescriptions = {
    heart: `
    The heart is a muscular organ found in most animals. This organ pumps blood through the blood vessels. Heart and blood vessels together make the circulatory system. The pumped blood carries oxygen and nutrients to the tissue, while carrying metabolic waste such as carbon dioxide to the lungs. In humans, the heart is approximately the size of a closed fist and is located between the lungs, in the middle compartment of the chest, called the mediastinum.

In humans, other mammals, and birds, the heart is divided into four chambers: upper left and right atria and lower left and right ventricles. Commonly, the right atrium and ventricle are referred together as the right heart and their left counterparts as the left heart. Fish, in contrast, have two chambers, an atrium and a ventricle, while most reptiles have three chambers. In a healthy heart, blood flows one way through the heart due to heart valves, which prevent backflow. The heart is enclosed in a protective sac, the pericardium, which also contains a small amount of fluid. The wall of the heart is made up of three layers: epicardium, myocardium, and endocardium. In all vertebrates, the heart has an asymmetric orientation, almost always on the left side. According to one theory, this is caused by a developmental axial twist in the early embryo.

The heart pumps blood with a rhythm determined by a group of pacemaker cells in the sinoatrial node. These generate an electric current that causes the heart to contract, traveling through the atrioventricular node and along the conduction system of the heart. In humans, deoxygenated blood enters the heart through the right atrium from the superior and inferior venae cavae and passes to the right ventricle. From here, it is pumped into pulmonary circulation to the lungs, where it receives oxygen and gives off carbon dioxide. Oxygenated blood then returns to the left atrium, passes through the left ventricle and is pumped out through the aorta into systemic circulation, traveling through arteries, arterioles, and capillaries—where nutrients and other substances are exchanged between blood vessels and cells, losing oxygen and gaining carbon dioxide—before being returned to the heart through venules and veins. The heart beats at a resting rate close to 72 beats per minute. Exercise temporarily increases the rate, but lowers it in the long term, and is good for heart health.

Cardiovascular diseases are the most common cause of death globally as of 2008, accounting for 30% of all human deaths. Of these more than three-quarters are a result of coronary artery disease and stroke. Risk factors include: smoking, being overweight, little exercise, high cholesterol, high blood pressure, and poorly controlled diabetes, among others. Cardiovascular diseases do not frequently have symptoms but may cause chest pain or shortness of breath. Diagnosis of heart disease is often done by the taking of a medical history, listening to the heart-sounds with a stethoscope, as well as with ECG, and echocardiogram which uses ultrasound. Specialists who focus on diseases of the heart are called cardiologists, although many specialties of medicine may be involved in treatment.
    `,
    brain: `
    The brain is an organ that serves as the center of the nervous system in all vertebrate and most invertebrate animals. It consists of nervous tissue and is typically located in the head (cephalization), usually near organs for special senses such as vision, hearing and olfaction. Being the most specialized organ, it is responsible for receiving information from the sensory nervous system, processing those information (thought, cognition, and intelligence) and the coordination of motor control (muscle activity and endocrine system).

While invertebrate brains arise from paired segmental ganglia (each of which is only responsible for the respective body segment) of the ventral nerve cord, vertebrate brains develop axially from the midline dorsal nerve cord as a vesicular enlargement at the rostral end of the neural tube, with centralized control over all body segments. All vertebrate brains can be embryonically divided into three parts: the forebrain (prosencephalon, subdivided into telencephalon and diencephalon), midbrain (mesencephalon) and hindbrain (rhombencephalon, subdivided into metencephalon and myelencephalon). The spinal cord, which directly interacts with somatic functions below the head, can be considered a caudal extension of the myelencephalon enclosed inside the vertebral column. Together, the brain and spinal cord constitute the central nervous system in all vertebrates.

In humans, the cerebral cortex contains approximately 14–16 billion neurons, and the estimated number of neurons in the cerebellum is 55–70 billion. Each neuron is connected by synapses to several thousand other neurons, typically communicating with one another via root-like protrusions called dendrites and long fiber-like extensions called axons, which are usually myelinated and carry trains of rapid micro-electric signal pulses called action potentials to target specific recipient cells in other areas of the brain or distant parts of the body. The prefrontal cortex, which controls executive functions, is particularly well developed in humans.

Physiologically, brains exert centralized control over a body's other organs. They act on the rest of the body both by generating patterns of muscle activity and by driving the secretion of chemicals called hormones. This centralized control allows rapid and coordinated responses to changes in the environment. Some basic types of responsiveness such as reflexes can be mediated by the spinal cord or peripheral ganglia, but sophisticated purposeful control of behavior based on complex sensory input requires the information integrating capabilities of a centralized brain.

The operations of individual brain cells are now understood in considerable detail but the way they cooperate in ensembles of millions is yet to be solved. Recent models in modern neuroscience treat the brain as a biological computer, very different in mechanism from a digital computer, but similar in the sense that it acquires information from the surrounding world, stores it, and processes it in a variety of ways.

This article compares the properties of brains across the entire range of animal species, with the greatest attention to vertebrates. It deals with the human brain insofar as it shares the properties of other brains. The ways in which the human brain differs from other brains are covered in the human brain article. Several topics that might be covered here are instead covered there because much more can be said about them in a human context. The most important that are covered in the human brain article are brain disease and the effects of brain damage.
    `,
    eyes: `An eye is a sensory organ that allows an organism to perceive visual information. It detects light and converts it into electro-chemical impulses in neurons (neurones). It is part of an organism's visual system.

In higher organisms, the eye is a complex optical system that collects light from the surrounding environment, regulates its intensity through a diaphragm, focuses it through an adjustable assembly of lenses to form an image, converts this image into a set of electrical signals, and transmits these signals to the brain through neural pathways that connect the eye via the optic nerve to the visual cortex and other areas of the brain.

Eyes with resolving power have come in ten fundamentally different forms, classified into compound eyes and non-compound eyes. Compound eyes are made up of multiple small visual units, and are common on insects and crustaceans. Non-compound eyes have a single lens and focus light onto the retina to form a single image. This type of eye is common in mammals, including humans.

The simplest eyes are pit eyes. They are eye-spots which may be set into a pit to reduce the angle of light that enters and affects the eye-spot, to allow the organism to deduce the angle of incoming light.

Eyes enable several photo response functions that are independent of vision. In an organism that has more complex eyes, retinal photosensitive ganglion cells send signals along the retinohypothalamic tract to the suprachiasmatic nuclei to effect circadian adjustment and to the pretectal area to control the pupillary light reflex.`,
    kidney: `In humans, the kidneys are two reddish-brown bean-shaped blood-filtering organs that are a multilobar, multipapillary form of mammalian kidneys, usually without signs of external lobulation. They are located on the left and right in the retroperitoneal space, and in adult humans are about 12 centimetres (4+1⁄2 inches) in length. They receive blood from the paired renal arteries; blood exits into the paired renal veins. Each kidney is attached to a ureter, a tube that carries excreted urine to the bladder.

The kidney participates in the control of the volume of various body fluids, fluid osmolality, acid-base balance, various electrolyte concentrations, and removal of toxins. Filtration occurs in the glomerulus: one-fifth of the blood volume that enters the kidneys is filtered. Examples of substances reabsorbed are solute-free water, sodium, bicarbonate, glucose, and amino acids. Examples of substances secreted are hydrogen, ammonium, potassium and uric acid. The nephron is the structural and functional unit of the kidney. Each adult human kidney contains around 1 million nephrons, while a mouse kidney contains only about 12,500 nephrons. The kidneys also carry out functions independent of the nephrons. For example, they convert a precursor of vitamin D to its active form, calcitriol; and synthesize the hormones erythropoietin and renin.

Chronic kidney disease (CKD) has been recognized as a leading public health problem worldwide. The global estimated prevalence of CKD is 13.4%, and patients with kidney failure needing renal replacement therapy are estimated between 5 and 7 million. Procedures used in the management of kidney disease include chemical and microscopic examination of the urine (urinalysis), measurement of kidney function by calculating the estimated glomerular filtration rate (eGFR) using the serum creatinine; and kidney biopsy and CT scan to evaluate for abnormal anatomy. Dialysis and kidney transplantation are used to treat kidney failure; one (or both sequentially) of these are almost always used when renal function drops below 15%. Nephrectomy is frequently used to cure renal cell carcinoma.

Renal physiology is the study of kidney function. Nephrology is the medical specialty which addresses diseases of kidney function: these include CKD, nephritic and nephrotic syndromes, acute kidney injury, and pyelonephritis. Urology addresses diseases of kidney (and urinary tract) anatomy: these include cancer, renal cysts, kidney stones and ureteral stones, and urinary tract obstruction.

The word “renal” is an adjective meaning “relating to the kidneys”, and its roots are French or late Latin. Whereas according to some opinions, "renal" should be replaced with "kidney" in scientific writings such as "kidney artery", other experts have advocated preserving the use of "renal" as appropriate including in "renal artery".`,
    liver: `The liver is a major metabolic organ exclusively found in vertebrate animals, which performs many essential biological functions such as detoxification of the organism, and the synthesis of proteins and various other biochemicals necessary for digestion and growth. In humans, it is located in the right upper quadrant of the abdomen, below the diaphragm and mostly shielded by the lower right rib cage. Its other metabolic roles include carbohydrate metabolism, the production of hormones, conversion and storage of nutrients such as glucose and glycogen, and the decomposition of red blood cells.

The liver is also an accessory digestive organ that produces bile, an alkaline fluid containing cholesterol and bile acids, which emulsifies and aids the breakdown of dietary fat. The gallbladder, a small hollow pouch that sits just under the right lobe of liver, stores and concentrates the bile produced by the liver, which is later excreted to the duodenum to help with digestion. The liver's highly specialized tissue, consisting mostly of hepatocytes, regulates a wide variety of high-volume biochemical reactions, including the synthesis and breakdown of small and complex organic molecules, many of which are necessary for normal vital functions. Estimates regarding the organ's total number of functions vary, but is generally cited as being around 500. For this reason, the liver has sometimes been described as the body's chemical factory.

It is not known how to compensate for the absence of liver function in the long term, although liver dialysis techniques can be used in the short term. Artificial livers have not been developed to promote long-term replacement in the absence of the liver. As of 2018, liver transplantation is the only option for complete liver failure.`,
    pancreas: `The pancreas is an organ of the digestive system and endocrine system of vertebrates. In humans, it is located in the abdomen behind the stomach and functions as a gland. The pancreas is a mixed or heterocrine gland, i.e., it has both an endocrine and a digestive exocrine function. 99% of the pancreas is exocrine and 1% is endocrine. As an endocrine gland, it functions mostly to regulate blood sugar levels, secreting the hormones insulin, glucagon, somatostatin and pancreatic polypeptide. As a part of the digestive system, it functions as an exocrine gland secreting pancreatic juice into the duodenum through the pancreatic duct. This juice contains bicarbonate, which neutralizes acid entering the duodenum from the stomach; and digestive enzymes, which break down carbohydrates, proteins and fats in food entering the duodenum from the stomach.

Inflammation of the pancreas is known as pancreatitis, with common causes including chronic alcohol use and gallstones. Because of its role in the regulation of blood sugar, the pancreas is also a key organ in diabetes mellitus. Pancreatic cancer can arise following chronic pancreatitis or due to other reasons, and carries a very poor prognosis, as it is often only identified after it has spread to other areas of the body.

The word pancreas comes from the Greek πᾶν (pân, "all") & κρέας (kréas, "flesh"). The function of the pancreas in diabetes has been known since at least 1889, with its role in insulin production identified in 1921.`,
    sm_intestine: `The small intestine or small bowel is an organ in the gastrointestinal tract where most of the absorption of nutrients from food takes place. It lies between the stomach and large intestine, and receives bile and pancreatic juice through the pancreatic duct to aid in digestion. The small intestine is about 5.5 metres (18 feet) long and folds many times to fit in the abdomen. Although it is longer than the large intestine, it is called the small intestine because it is narrower in diameter.

The small intestine has three distinct regions – the duodenum, jejunum, and ileum. The duodenum, the shortest, is where preparation for absorption through small finger-like protrusions called villi begins. The jejunum is specialized for the absorption through its lining by enterocytes: small nutrient particles which have been previously digested by enzymes in the duodenum. The main function of the ileum is to absorb vitamin B12, bile salts, and whatever products of digestion that were not absorbed by the jejunum.

`,
    lung: `The lungs are the main organs of the respiratory system in many terrestrial animals, including all tetrapod vertebrates and a small number of amphibious fish (lungfish and bichirs), pulmonate gastropods (land snails and slugs, which have analogous pallial lungs), and some arachnids (tetrapulmonates such as spiders and scorpions, which have book lungs). Their function is to conduct gas exchange by extracting oxygen from the air into the bloodstream via diffusion directly across the humidified airway epithelia, and to release carbon dioxide from the bloodstream out into the atmosphere, a process also known as respiration. This article primarily concerns with the lungs of tetrapods (particularly those of humans), which are paired and located on either side of the heart, occupying most of the volume of the thoracic cavity, and are homologous to the swim bladders in ray-finned fish.

The movements of air in and out of the lungs is called ventilation or breathing, which is driven by different muscular systems in different species. Amniotes like mammals, reptiles and birds use different dedicated respiratory muscles to facilitate breathing, while in primitive tetrapods, air was driven into the lungs by the pharyngeal muscles via buccal pumping, a mechanism still seen in amphibians. In humans, the main muscles of respiration that drives breathing are the diaphragm and intercostal muscles, while other core and limb muscles might also be recruited as accessory muscles in situations of respiratory distress. The lungs also provide airflow that makes vocalization (including human speech) possible.

Human lungs, like other tetrapods, are paired with one on the left and one on the right. Due to the leftward rotation of the heart, the right lung is bigger and heavier than the left, and the two lungs together weigh approximately 1.3 kilograms (2.9 lb). The lungs are part of the lower respiratory tract that begins at the trachea and branches into the bronchi and bronchioles, and which receive fresh air inhaled (breathed in) via the conducting zone. The conducting zone ends at the terminal bronchioles, which divide into the respiratory bronchioles of the respiratory zone and further divide into alveolar ducts that give rise to the alveolar sacs that contain the alveoli, where majority of gas exchange takes place. Alveoli are also sparsely present on the walls of the respiratory bronchioles and alveolar ducts. Together, the lungs contain approximately 2,400 kilometres (1,500 mi) of airways and 300 to 500 million alveoli. Each lung is enveloped by a serous membranes called pleurae, which also overlays the inside surface of the rib cage; the two membranes (called the visceral and parietal pleurae, respectively) form an enclosing sac known as the pleural cavity, which contains a lubricating film of serous fluid (pleural fluid) that separates the two pleurae and reduces the friction of sliding movements between them, allowing for easier expansion of the lungs during breathing. The visceral pleura also invaginates into each lung as fissures, which divides the lung into independent sections called lobes. The right lung typically has three lobes, and the left has two. The lobes are further divided into bronchopulmonary segments and pulmonary lobules.

The lungs have two unique blood supplies: the pulmonary circulation, which receives deoxygenated blood from the right heart via the pulmonary arteries, exchanges oxygen and carbon dioxide across the alveolar–capillary barrier, before returning the re-oxygenated blood to the left heart via the pulmonary veins for pumping to the rest of the body; and the bronchial circulation, which is part of the systemic circulation that provides a separate supply of oxygenated blood to the tissue of the lungs.  

The lung can be affected by a number of respiratory diseases, including pneumonia, pulmonary fibrosis and lung cancer. Chronic obstructive pulmonary disease includes chronic bronchitis and emphysema, and are commonly related to smoking or exposure to air pollutants. A number of occupational lung diseases can be caused by substances such as coal dust, asbestos fibres and crystalline silica dust. Diseases such as acute bronchitis and asthma can also affect lung function, although such conditions are technically airway diseases rather than lung diseases. Medical terms related to the lung often begin with pulmo-, from the Latin pulmonarius (meaning "of the lungs") as in pulmonology, or with pneumo- (from Greek πνεύμων, meaning "lung") as in pneumonia.

In embryonic development, the lungs begin to develop as an outpouching of the foregut, a tube which goes on to form the upper part of the digestive system. When the lungs are formed the fetus is held in the fluid-filled amniotic sac and so they do not function to breathe. Blood is also diverted from the lungs through the ductus arteriosus. At birth, air begins to pass through the lungs, and the diversionary duct closes, so that the lungs can begin to respire. The lungs only fully develop in early childhood.`,
    skin: `Skin is the layer of usually soft, flexible outer tissue covering the body of a vertebrate animal, with three main functions: protection, regulation, and sensation.

Other animal coverings, such as the arthropod exoskeleton, have different developmental origin, structure and chemical composition. The adjective cutaneous means "of the skin" (from Latin cutis 'skin'). In mammals, the skin is an organ of the integumentary system made up of multiple layers of ectodermal tissue and guards the underlying muscles, bones, ligaments, and internal organs. Skin of a different nature exists in amphibians, reptiles, and birds. Skin (including cutaneous and subcutaneous tissues) plays crucial roles in formation, structure, and function of extraskeletal apparatus such as horns of bovids (e.g., cattle) and rhinos, cervids' antlers, giraffids' ossicones, armadillos' osteoderm, and os penis/os clitoris.

All mammals have some hair on their skin, even marine mammals like whales, dolphins, and porpoises that appear to be hairless. The skin interfaces with the environment and is the first line of defense from external factors. For example, the skin plays a key role in protecting the body against pathogens and excessive water loss. Its other functions are insulation, temperature regulation, sensation, and the production of vitamin D folates. Severely damaged skin may heal by forming scar tissue. This is sometimes discoloured and depigmented. The thickness of skin also varies from location to location on an organism. In humans, for example, the skin located under the eyes and around the eyelids is the thinnest skin on the body at 0.5 mm thick and is one of the first areas to show signs of aging such as "crows feet" and wrinkles. The skin on the palms and the soles of the feet is the thickest skin on the body at 4 mm thick. The speed and quality of wound healing in skin is promoted by estrogen.

Fur is dense hair. Primarily, fur augments the insulation the skin provides but can also serve as a secondary sexual characteristic or as camouflage. On some animals, the skin is very hard and thick and can be processed to create leather. Reptiles and most fish have hard protective scales on their skin for protection, and birds have hard feathers, all made of tough beta-keratins. Amphibian skin is not a strong barrier, especially regarding the passage of chemicals via skin, and is often subject to osmosis and diffusive forces. For example, a frog sitting in an anesthetic solution would be sedated quickly as the chemical diffuses through its skin. Amphibian skin plays key roles in everyday survival and their ability to exploit a wide range of habitats and ecological conditions.

On 11 January 2024, biologists reported the discovery of the oldest known skin, fossilized about 289 million years ago, and possibly the skin from an ancient reptile.`,
    lg_intestine: `The large intestine, also known as the large bowel, is the last part of the gastrointestinal tract and of the digestive system in tetrapods. Water is absorbed here and the remaining waste material is stored in the rectum as feces before being removed by defecation. The colon is the longest portion of the large intestine, and the terms are often used interchangeably but most sources define the large intestine as the combination of the cecum, colon, rectum, and anal canal. Some other sources exclude the anal canal.

In humans, the large intestine begins in the right iliac region of the pelvis, just at or below the waist, where it is joined to the end of the small intestine at the cecum, via the ileocecal valve. It then continues as the colon ascending the abdomen, across the width of the abdominal cavity as the transverse colon, and then descending to the rectum and its endpoint at the anal canal. Overall, in humans, the large intestine is about 1.5 metres (5 ft) long, which is about one-fifth of the whole length of the human gastrointestinal tract.`,
    prostate: `The prostate (/ˈprɒs.teɪt/) is both an accessory gland of the male reproductive system and a muscle-driven mechanical switch between urination and ejaculation. It is found in all male mammals. It differs between species anatomically, chemically, and physiologically. Anatomically, the prostate is found below the bladder, with the urethra passing through it. It is described in gross anatomy as consisting of lobes and in microanatomy by zone. It is surrounded by an elastic, fibromuscular capsule and contains glandular tissue, as well as connective tissue.

The prostate produces and contains fluid that forms part of semen, the substance emitted during ejaculation as part of the male sexual response. This prostatic fluid is slightly alkaline, milky or white in appearance. The alkalinity of semen helps neutralize the acidity of the vaginal tract, prolonging the lifespan of sperm. The prostatic fluid is expelled in the first part of ejaculate, together with most of the sperm, because of the action of smooth muscle tissue within the prostate. In comparison with the few spermatozoa expelled together with mainly seminal vesicular fluid, those in prostatic fluid have better motility, longer survival, and better protection of genetic material.

Disorders of the prostate include enlargement, inflammation, infection, and cancer. The word prostate comes from Ancient Greek προστάτης, prostátēs, meaning "one who stands before", "protector", "guardian", with the term originally used to describe the seminal vesicles.`,
    pelvis: `The pelvis (pl.: pelves or pelvises) is the lower part of an anatomical trunk, between the abdomen and the thighs (sometimes also called pelvic region), together with its embedded skeleton (sometimes also called bony pelvis or pelvic skeleton).

The pelvic region of the trunk includes the bony pelvis, the pelvic cavity (the space enclosed by the bony pelvis), the pelvic floor, below the pelvic cavity, and the perineum, below the pelvic floor. The pelvic skeleton is formed in the area of the back, by the sacrum and the coccyx and anteriorly and to the left and right sides, by a pair of hip bones.

The two hip bones connect the spine with the lower limbs. They are attached to the sacrum posteriorly, connected to each other anteriorly, and joined with the two femurs at the hip joints. The gap enclosed by the bony pelvis, called the pelvic cavity, is the section of the body underneath the abdomen and mainly consists of the reproductive organs and the rectum, while the pelvic floor at the base of the cavity assists in supporting the organs of the abdomen.

In mammals, the bony pelvis has a gap in the middle, significantly larger in females than in males. Their offspring pass through this gap when they are born.`,
    legs: `A leg is a weight-bearing and locomotive anatomical structure, usually having a columnar shape. During locomotion, legs function as "extensible struts". The combination of movements at all joints can be modeled as a single, linear element capable of changing length and rotating about an omnidirectional "hip" joint.

As an anatomical animal structure, it is used for locomotion. The distal end is often modified to distribute force (such as a foot). Most animals have an even number of legs.

As a component of furniture, it is used for the economy of materials needed to provide the support for the useful surface, such as the table top or chair seat.`,
    blood_vasculature: `The circulatory system is a system of organs that includes the heart, blood vessels, and blood which is circulated throughout the entire body of a human or other vertebrate. It includes the cardiovascular system, or vascular system, that consists of the heart and blood vessels (from Greek kardia meaning heart, and from Latin vascula meaning vessels). The circulatory system has two divisions, a systemic circulation or circuit, and a pulmonary circulation or circuit. Some sources use the terms cardiovascular system and vascular system interchangeably with circulatory system.

The network of blood vessels are the great vessels of the heart including large elastic arteries, and large veins; other arteries, smaller arterioles, capillaries that join with venules (small veins), and other veins. The circulatory system is closed in vertebrates, which means that the blood never leaves the network of blood vessels. Some invertebrates such as arthropods have an open circulatory system. Diploblasts such as sponges, and comb jellies lack a circulatory system.

Blood is a fluid consisting of plasma, red blood cells, white blood cells, and platelets; it is circulated around the body carrying oxygen and nutrients to the tissues and collecting and disposing of waste materials. Circulated nutrients include proteins and minerals and other components include hemoglobin, hormones, and gases such as oxygen and carbon dioxide. These substances provide nourishment, help the immune system to fight diseases, and help maintain homeostasis by stabilizing temperature and natural pH.

In vertebrates, the lymphatic system is complementary to the circulatory system. The lymphatic system carries excess plasma (filtered from the circulatory system capillaries as interstitial fluid between cells) away from the body tissues via accessory routes that return excess fluid back to blood circulation as lymph. The lymphatic system is a subsystem that is essential for the functioning of the blood circulatory system; without it the blood would become depleted of fluid.

The lymphatic system also works with the immune system. The circulation of lymph takes much longer than that of blood and, unlike the closed (blood) circulatory system, the lymphatic system is an open system. Some sources describe it as a secondary circulatory system.

The circulatory system can be affected by many cardiovascular diseases. Cardiologists are medical professionals which specialise in the heart, and cardiothoracic surgeons specialise in operating on the heart and its surrounding areas. Vascular surgeons focus on disorders of the blood vessels, and lymphatic vessels.`,
    urinary_bladder: `The bladder is a hollow organ in humans and other vertebrates that stores urine from the kidneys. In placental mammals, urine enters the bladder via the ureters and exits via the urethra during urination. In humans, the bladder is a distensible organ that sits on the pelvic floor. The typical adult human bladder will hold between 300 and 500 ml (10 and 17 fl oz) before the urge to empty occurs, but can hold considerably more.

The Latin phrase for "urinary bladder" is vesica urinaria, and the term vesical or prefix vesico- appear in connection with associated structures such as vesical veins. The modern Latin word for "bladder" – cystis – appears in associated terms such as cystitis (inflammation of the bladder).`,
    ureter: `The ureters are tubes composed of smooth muscle that transport urine from the kidneys to the urinary bladder. In an adult human, the ureters typically measure 20 to 30 centimeters in length and about 3 to 4 millimeters in diameter. They are lined with urothelial cells, a form of transitional epithelium, and feature an extra layer of smooth muscle in the lower third to aid in peristalsis. The ureters can be affected by a number of diseases, including urinary tract infections and kidney stone. Stenosis is when a ureter is narrowed, due to for example chronic inflammation. Congenital abnormalities that affect the ureters can include the development of two ureters on the same side or abnormally placed ureters. Additionally, reflux of urine from the bladder back up the ureters is a condition commonly seen in children.

The ureters have been identified for at least two thousand years, with the word "ureter" stemming from the stem uro- relating to urinating and seen in written records since at least the time of Hippocrates. It is, however, only since the 1500s that the term "ureter" has been consistently used to refer to the modern structure, and only since the development of medical imaging in the 1900s that techniques such as X-ray, CT, and ultrasound have been able to view the ureters. The ureters are also seen from the inside using a flexible camera, called ureteroscopy, which was first described in 1964.`,
    larynx: `The larynx (/ˈlærɪŋks/), commonly called the voice box, is an organ in the top of the neck involved in breathing, producing sound and protecting the trachea against food aspiration. The opening of larynx into pharynx known as the laryngeal inlet is about 4–5 centimeters in diameter. The larynx houses the vocal cords, and manipulates pitch and volume, which is essential for phonation. It is situated just below where the tract of the pharynx splits into the trachea and the esophagus. The word 'larynx' (pl.: larynges) comes from the Ancient Greek word lárunx ʻlarynx, gullet, throatʼ.`,
    lymph_node: `A lymph node, or lymph gland, is a kidney-shaped organ of the lymphatic system and the adaptive immune system. A large number of lymph nodes are linked throughout the body by the lymphatic vessels. They are major sites of lymphocytes that include B and T cells. Lymph nodes are important for the proper functioning of the immune system, acting as filters for foreign particles including cancer cells, but have no detoxification function.

In the lymphatic system, a lymph node is a secondary lymphoid organ. A lymph node is enclosed in a fibrous capsule and is made up of an outer cortex and an inner medulla.

Lymph nodes become inflamed or enlarged in various diseases, which may range from trivial throat infections to life-threatening cancers. The condition of lymph nodes is very important in cancer staging, which decides the treatment to be used and determines the prognosis. Lymphadenopathy refers to glands that are enlarged or swollen. When inflamed or enlarged, lymph nodes can be firm or tender.`,
    bronchus: `A bronchus (/ˈbrɒŋkəs/ BRONG-kəs; pl.: bronchi, /ˈbrɒŋkaɪ/ BRONG-ky) is a passage or airway in the lower respiratory tract that conducts air into the lungs. The first or primary bronchi to branch from the trachea at the carina are the right main bronchus and the left main bronchus. These are the widest bronchi, and enter the right lung, and the left lung at each hilum. The main bronchi branch into narrower secondary bronchi or lobar bronchi, and these branch into narrower tertiary bronchi or segmental bronchi. Further divisions of the segmental bronchi are known as 4th order, 5th order, and 6th order segmental bronchi, or grouped together as subsegmental bronchi. The bronchi, when too narrow to be supported by cartilage, are known as bronchioles. No gas exchange takes place in the bronchi.`,
    palatine_tonsil: `Palatine tonsils, commonly called the tonsils and occasionally called the faucial tonsils, are tonsils located on the left and right sides at the back of the throat, which can often be seen as flesh-colored, pinkish lumps. Tonsils only present as "white lumps" if they are inflamed or infected with symptoms of exudates (pus drainage) and severe swelling.

Tonsillitis is an inflammation of the tonsils and will often, but not necessarily, cause a sore throat and fever. In chronic cases, tonsillectomy may be indicated.`,
    spinal_cord: `The spinal cord is a long, thin, tubular structure made up of nervous tissue that extends from the medulla oblongata in the lower brainstem to the lumbar region of the vertebral column (backbone) of vertebrate animals. The center of the spinal cord is hollow and contains a structure called the central canal, which contains cerebrospinal fluid. The spinal cord is also covered by meninges and enclosed by the neural arches. Together, the brain and spinal cord make up the central nervous system.

In humans, the spinal cord is a continuation of the brainstem and anatomically begins at the occipital bone, passing out of the foramen magnum and then enters the spinal canal at the beginning of the cervical vertebrae. The spinal cord extends down to between the first and second lumbar vertebrae, where it tapers to become the cauda equina. The enclosing bony vertebral column protects the relatively shorter spinal cord. It is around 45 cm (18 in) long in adult men and around 43 cm (17 in) long in adult women. The diameter of the spinal cord ranges from 13 mm (1⁄2 in) in the cervical and lumbar regions to 6.4 mm (1⁄4 in) in the thoracic area.

The spinal cord functions primarily in the transmission of nerve signals from the motor cortex to the body, and from the afferent fibers of the sensory neurons to the sensory cortex. It is also a center for coordinating many reflexes and contains reflex arcs that can independently control reflexes. It is also the location of groups of spinal interneurons that make up the neural circuits known as central pattern generators. These circuits are responsible for controlling motor instructions for rhythmic movements such as walking.`,
    spleen: `The spleen is an organ found in almost all vertebrates. Similar in structure to a large lymph node, it acts primarily as a blood filter. The word spleen comes from Ancient Greek σπλήν (splḗn).

The spleen plays very important roles in regard to red blood cells (erythrocytes) and the immune system. It removes old red blood cells and holds a reserve of blood, which can be valuable in case of hemorrhagic shock, and also recycles iron. As a part of the mononuclear phagocyte system, it metabolizes hemoglobin removed from senescent red blood cells. The globin portion of hemoglobin is degraded to its constitutive amino acids, and the heme portion is metabolized to bilirubin, which is removed in the liver.

The spleen houses antibody-producing lymphocytes in its white pulp and monocytes which remove antibody-coated bacteria and antibody-coated blood cells by way of blood and lymph node circulation. These monocytes, upon moving to injured tissue (such as the heart after myocardial infarction), turn into dendritic cells and macrophages while promoting tissue healing. The spleen is a center of activity of the mononuclear phagocyte system and is analogous to a large lymph node, as its absence causes a predisposition to certain infections.

In humans, the spleen is purple in color and is in the left upper quadrant of the abdomen. The surgical process to remove the spleen is known as a splenectomy.`,
    thymus: `The thymus (pl.: thymuses or thymi) is a specialized primary lymphoid organ of the immune system. Within the thymus, thymus cell lymphocytes or T cells mature. T cells are critical to the adaptive immune system, where the body adapts to specific foreign invaders. The thymus is located in the upper front part of the chest, in the anterior superior mediastinum, behind the sternum, and in front of the heart. It is made up of two lobes, each consisting of a central medulla and an outer cortex, surrounded by a capsule.

The thymus is made up of immature T cells called thymocytes, as well as lining cells called epithelial cells which help the thymocytes develop. T cells that successfully develop react appropriately with MHC immune receptors of the body (called positive selection) and not against proteins of the body (called negative selection). The thymus is the largest and most active during the neonatal and pre-adolescent periods. By the early teens, the thymus begins to decrease in size and activity and the tissue of the thymus is gradually replaced by fatty tissue. Nevertheless, some T cell development continues throughout adult life.

Abnormalities of the thymus can result in a decreased number of T cells and autoimmune diseases such as autoimmune polyendocrine syndrome type 1 and myasthenia gravis. These are often associated with cancer of the tissue of the thymus, called thymoma, or tissues arising from immature lymphocytes such as T cells, called lymphoma. Removal of the thymus is called thymectomy. Although the thymus has been identified as a part of the body since the time of the Ancient Greeks, it is only since the 1960s that the function of the thymus in the immune system has become clearer.`,
    trachea: `The trachea (pl.: tracheae or tracheas), also known as the windpipe, is a cartilaginous tube that connects the larynx to the bronchi of the lungs, allowing the passage of air, and so is present in almost all animals lungs. The trachea extends from the larynx and branches into the two primary bronchi. At the top of the trachea, the cricoid cartilage attaches it to the larynx. The trachea is formed by a number of horseshoe-shaped rings, joined together vertically by overlying ligaments, and by the trachealis muscle at their ends. The epiglottis closes the opening to the larynx during swallowing.

The trachea begins to form in the second month of embryo development, becoming longer and more fixed in its position over time. It is epithelium lined with column-shaped cells that have hair-like extensions called cilia, with scattered goblet cells that produce protective mucins. The trachea can be affected by inflammation or infection, usually as a result of a viral illness affecting other parts of the respiratory tract, such as the larynx and bronchi, called croup, that can result in a cough. Infection with bacteria usually affects the trachea only and can cause narrowing or even obstruction. As a major part of the respiratory tract, when obstructed the trachea prevents air entering the lungs and so a tracheostomy may be required if the trachea is obstructed. Additionally, during surgery if mechanical ventilation is required when a person is sedated, a tube is inserted into the trachea, called intubation.

The word trachea is used to define a very different organ in invertebrates than in vertebrates. Insects have an open respiratory system made up of spiracles, tracheae, and tracheoles to transport metabolic gases to and from tissues.`,
    spine: `Each vertebra (pl.: vertebrae) is an irregular bone with a complex structure composed of bone and some hyaline cartilage, that make up the vertebral column or spine, of vertebrates. The proportions of the vertebrae differ according to their spinal segment and the particular species.

The basic configuration of a vertebra varies; the bone is the body, and the central part of the body is the centrum. The upper and lower surfaces of the vertebra body give attachment to the intervertebral discs. The posterior part of a vertebra forms a vertebral arch, in eleven parts, consisting of two pedicles (pedicle of vertebral arch), two laminae, and seven processes. The laminae give attachment to the ligamenta flava (ligaments of the spine). There are vertebral notches formed from the shape of the pedicles, which form the intervertebral foramina when the vertebrae articulate. These foramina are the entry and exit conduits for the spinal nerves. The body of the vertebra and the vertebral arch form the vertebral foramen, the larger, central opening that accommodates the spinal canal, which encloses and protects the spinal cord.

Vertebrae articulate with each other to give strength and flexibility to the spinal column, and the shape at their back and front aspects determines the range of movement. Structurally, vertebrae are essentially alike across the vertebrate species, with the greatest difference seen between an aquatic animal and other vertebrate animals. As such, vertebrates take their name from the vertebrae that compose the vertebral column.`,
    rectus_femoris: `The quadriceps femoris muscle (/ˈkwɒdrɪsɛps ˈfɛmərɪs/, also called the quadriceps extensor, quadriceps or quads) is a large muscle group that includes the four prevailing muscles on the front of the thigh. It is the sole extensor muscle of the knee, forming a large fleshy mass which covers the front and sides of the femur. The name derives from Latin four-headed muscle of the femur.`,
    cricoarytenoid: `The cricoarytenoid is a muscle involved in vocal cord movement.`,
    cystic_duct: `The cystic duct typically measures (sources differ) 2–4 cm/2–3 cm in length (though its length has been known to range from 0.5 cm to 9 cm), and 2–3 mm in diameter. It is often tortuous.

It is the distal continuation of the neck of the gallbladder, from where it is directed inferoposteriorly and to the left/medially (this occurs in half of individuals). It typically terminates by uniting with the common hepatic duct to form the bile duct (usually anterior to the right hepatic artery). It usually joins the common bile duct from the right lateral side (forming an oblique angle between the two), and at such a distance that the bile duct is twice as long as the common hepatic duct. It often fuses with the common hepatic duct before actually opening into it after a variable distance (this arrangement may have the purpose of directing bile flow distally instead of back towards the liver).

`,
    gallbladder: `In vertebrates, the gallbladder, also known as the cholecyst, is a small hollow organ where bile is stored and concentrated before it is released into the small intestine. In humans, the pear-shaped gallbladder lies beneath the liver, although the structure and position of the gallbladder can vary significantly among animal species. It receives bile, produced by the liver, via the common hepatic duct, and stores it. The bile is then released via the common bile duct into the duodenum, where the bile helps in the digestion of fats.

The gallbladder can be affected by gallstones, formed by material that cannot be dissolved – usually cholesterol or bilirubin, a product of hemoglobin breakdown. These may cause significant pain, particularly in the upper-right corner of the abdomen, and are often treated with removal of the gallbladder (called a cholecystectomy). Cholecystitis, inflammation of the gallbladder, has a wide range of causes, including result from the impaction of gallstones, infection, and autoimmune disease.

`,
    urethra: `The urethra (pl.: urethras or urethrae) is the tube that connects the mammalian urinary bladder to the urinary meatus. In placental mammals, the urethra transports urine through the penis or vulva during urination and semen through the penis during ejaculation. In non-mammalian vertebrates, the urethra also transports semen but is separate from the urinary tract.

The external urethral sphincter is a striated muscle that allows voluntary control over urination. The internal sphincter, formed by the involuntary smooth muscles lining the bladder neck and urethra, receives its nerve supply by the sympathetic division of the autonomic nervous system. The internal sphincter is present both in males and females.

`,
    hyoid: `The hyoid bone (lingual bone or tongue-bone) (/ˈhaɪɔɪd/) is a horseshoe-shaped bone situated in the anterior midline of the neck between the chin and the thyroid cartilage. At rest, it lies between the base of the mandible and the third cervical vertebra.

Unlike other bones, the hyoid is only distantly articulated to other bones by muscles or ligaments. It is the only bone in the human body that is not connected to any other bones. The hyoid is anchored by muscles from the anterior, posterior and inferior directions, and aids in tongue movement and swallowing. The hyoid bone provides attachment to the muscles of the floor of the mouth and the tongue above, the larynx below, and the epiglottis and pharynx behind.`
};

export default organDescriptions;